### ISSUE TITLE
PowerShell command naming not following standard convention

### ISSUE THREAD

**Issue by fubar-coder** [crimcol/Alt.FluentMigrator.VStudio#1]
The standard naming convention for PowerShell commands is `Verb-Noun`, so I suggest that the commands are renamed to:

```pwsh
Add-FluentMigrator "Name"
Update-FluentDatabase
Rollback-FluentDatabase
```

Thank you for supporting FluentMigrator 👍

**Comment by crimcol** [comment]
@fubar-coder I've created pull request for command renaming: 
[Rename commands to follow naming convention](https://github.com/crimcol/FluentMigrator.VStudio/pull/2)
Please let me know if you have any comments.

Note: 'Rollback' verb is not approved in PowerShell, so I've to add -DisableNameChecking parameter for package installation.

**Comment by crimcol** [comment]
Changes committed.
