### ISSUE TITLE
Add-FluentMigration function with -AddScript option Creates Script, but not Migration

### ISSUE THREAD

**Issue by git-youzer** [crimcol/Alt.FluentMigrator.VStudio#10]
https://github.com/crimcol/Alt.FluentMigrator.VStudio/blob/bfb270a55becfd9f0a822cd8c1da735d36533fbc/src/Alt.FluentMigrator.VStudio.psm1#L154

Script file is created, but the Migration file is not.
Seems to be an error when setting the Value = 2

![image](https://user-images.githubusercontent.com/6665701/121573659-1f074600-c9eb-11eb-854f-f029ed61b0d9.png)

**Comment by crimcol** [comment]
Hi @git-youzer, do you use .NET Core project?
It looks like it fails only in Core projects, so I will need to fix it.

**Comment by crimcol** [comment]
Issue solved in **v1.3.2**.
